## 第十章 習題

## 10.1 基本運算

## 1. 設 𝑎=np.array([67.4, 76.1, 73.7, 84.9])，試依序完成下列各題：

In [1]:
import numpy as np
np.set_printoptions(3)
𝑎=np.array([67.4, 76.1, 73.7, 84.9])

### (a) 將 𝑎 裡的每個元素開根號。

In [2]:
print(np.sqrt(a))

[8.21  8.724 8.585 9.214]


### (b) 取出 𝑎 中的小數部分。

In [3]:
print(np.modf(a)[0])

[0.4 0.1 0.7 0.9]


### (c) 取出 𝑎 的元素中，整數部分是偶數的元素（本例應提取出 76.1 和 84.9）。

In [4]:
print(a[np.modf(a)[1]%2==0])

[76.1 84.9]


### (d) 取出 𝑎 的元素中，最小之數的索引。

In [5]:
print(np.argmin(a))

0


### (e) 提取陣列 𝑎 中，大於 70 的數，並將它們平均。

In [6]:
print(sum(a[a>70]))

234.70000000000002


## 2. 設
$$
𝑎 =
\begin{bmatrix}
5 & 12 & 8 & 14 \\
6 & 1 & 8 & 14 \\
21 & 17 & 3 & 0 \\
\end{bmatrix}
$$
，試依序作答下列各題：

### (a) 計算 𝑎 的平均值，並設之為 𝑚。

In [7]:
a=np.array([[5,12,8,14],[6,1,8,14],[21,17,3,0]])
m=a.mean()
print(round(m,3))

9.083


### (b) 提取 𝑎 中，大於 𝑚 之元素，並將它們平均。

In [8]:
print((a[a>m]).mean())

15.6


### (c) 提取 𝑎 中，小於等於 𝑚 之元素，並將它們平均。

In [9]:
print(round((a[a<=m]).mean(),3))

4.429


### (d) 建立一個陣列 𝑏，形狀與 𝑎 相同，且如果 𝑎 裡的元素值大於 𝑚 的話，陣列 𝑏 裡相對應的元素值就為 1，否則 𝑏 的元素值就為 0。

## 3. 設 𝑎 =
$$
a=
\begin{bmatrix}
12 & 10 & 0 & 9 & 12 \\
3 & 17 & 18 & −3 & 3 \\
0 & 7 & 8 & 5 & 0 \\
\end{bmatrix}
$$
，試依序作答下列各題

### (a) 找出 𝑎 中，每一個橫列的最大值。

In [10]:
a=np.array([[12,10,0,9,12],[3,17,18,-3,3],[0,7,8,5,0]])
print(np.max(a,axis=1))

[12 18  8]


### (b) 找出 𝑎 中，每一個直行的最小值的索引。

In [11]:
print(np.argmin(a,axis=0))

[2 2 0 1 2]


### (c) 將陣列 𝑎 的每一個橫列加總。

In [12]:
print(np.sum(a,axis=1))

[43 38 20]


### (d) 將陣列 𝑎 的每一個直行平均。

In [13]:
np.set_printoptions(3)
print(np.mean(a,axis=0))

[ 5.    11.333  8.667  3.667  5.   ]


### (e) 找出陣列 𝑎 的元素值為 0 之列和行的索引。

In [14]:
row,col=np.where(a==0)
print(row,col)

[0 2 2] [2 0 4]


### (f) 找出陣列 𝑎 的元素中，大於 0 之元素的總和。

In [15]:
print(a[a>0].sum())

104


### (g) 找出陣列 𝑎 的最大值之列和行的索引。

In [16]:
row,col=np.where(a==a.max())
print(row,col)

[1] [2]


### (h) 提取陣列 𝑎 中，元素值不包含 0 的直行。

In [17]:
print(a[:,~np.any(a == 0, axis=0)])

[[10  9]
 [17 -3]
 [ 7  5]]


### (i) 陣列 𝑎 中有兩個直行的元素都相同，試去掉其中一個直行。

In [18]:
print(np.unique(a,axis=1))

[[ 0  9 10 12]
 [18 -3 17  3]
 [ 8  5  7  0]]


### (j) 從 𝑎 中分別提取不包含元素 5 的橫列和直行。

In [19]:
print(a[~np.any(a == 5, axis=1)], a[:, ~np.any(a == 5, axis=0)])

[[12 10  0  9 12]
 [ 3 17 18 -3  3]] [[12 10  0 12]
 [ 3 17 18  3]
 [ 0  7  8  0]]


### (k) 找出陣列 𝑎 中，絕對值為 3 之元素的個數。

In [20]:
print(len(a[abs(a)==3]))

3


## 4. 若 𝑎 為一個 6 × 4 的陣列，試回答下列問題：

### (a) 在 𝑎 中，如果一維索引為分別為 7, 9, 14，則在陣列 𝑎 中，列和行的索引為何？

In [21]:
a=np.arange(24).reshape((6,4))
row,col=np.where(np.isin(a,[7,9,14]))
print(row,col)

[1 2 3] [3 1 2]


### (b) 若元素的列和行的索引分別為 [0,3,4,2] 和 [1,3,2,0]，則這些元素的一維索引分別為何？

In [22]:
m=[0,3,4,2]
n= [1,3,2,0]
print(a[m,n])

[ 1 15 18  8]


## 5. 設
$$
𝑎 =
\begin{bmatrix}
0 & 1 & 2 & 3 & 4 \\
2 & 3 & 4 & 0 & 1 \\
4 & 0 & 1 & 2 & 3 \\
1 & 2 & 3 & 4 & 0 \\
3 & 4 & 0 & 1 & 2 \\
\end{bmatrix}
$$
，如果把列和行的索引看成是坐標 (𝑟, 𝑐)，試作答下列各題

### (a) 試找出離坐標 (2,2) 最近，且元素值為 4 的坐標（答案為 (1,2)）。

In [23]:
a=np.array([[0,1,2,3,4],[2,3,4,0,1],[4,0,1,2,3],[1,2,3,4,0],[3,4,0,1,2]])
def getpoint(target,item):
    indexs=np.where(a==item)
    dist=np.sqrt((indexs[0] - target[0]) ** 2 + (indexs[1] - target[1]) ** 2)
    min_dist_index= np.argmin(dist)
    return (indexs[0][min_dist_index], indexs[1][min_dist_index])
print(getpoint((2,2),4))

(1, 2)


### (b) 試找出離坐標 (4,3) 最近，且元素值為 0 的坐標（答案為 (4,2)）。

In [24]:
print(getpoint((4,3),0))

(4, 2)


### (c) 試找出離坐標 (4,0) 最近，且元素值為 2 的坐標（答案為 (3,1)）。

In [25]:
print(getpoint((4,0),2))

(3, 1)


### (d) 找出相距最遠的兩個 4 的坐標（答案應為 (0,4) 和 (4,1)）。

In [26]:
indexs=np.argwhere(a==4)
#print(indexs)
dist = np.sqrt(np.sum((indexs[:, None] - indexs) ** 2, axis=-1))
#print(dist)
i, j = np.unravel_index(np.argmax(dist), dist.shape)
print(indexs[i],indexs[j])

[0 4] [4 1]


### (e) 找出陣列 𝑎 中，值為 0 的元素共有幾個。

In [27]:
indexs=np.argwhere(a==0)
#print(indexs)
print(len(indexs))

5


## 6. 試設計一函數 prime_list(𝑛)，可以找出小於 𝑛 的所有質數

In [28]:
def isprime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
def prime_list(n):
    return [n for n in np.arange(1, n+1) if isprime(n)]
print(prime_list(100))

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


## 7. 試以下面的方程式定義函數 find_pi(𝑛)，用來計算 𝜋 的近似值，並計算當 𝑛 = 2 和 𝑛 = 10時，𝜋 的近似值為多少：

In [52]:
def find_pi(k):
    return sum([(1.0/(16.0**k))*(4.0/(8.0*k+1.0)-2.0/(8.0*k+4.0)-1.0/(8.0*k+5.0)-1.0/(8.0*k+6.0)) for k in np.arange(0, k+1)])
print(find_pi(2))
print(find_pi(10))

3.1415873903465816
3.141592653589793


## 10.2 資料的排序

## 8. 設 𝑎 = (12, 7, 23, 76, 23, 77, 54, 33, 98)，試取出 𝑎 裡的偶數，然後將它們從小到大排序。

In [55]:
𝑎 = np.array([12, 7, 23, 76, 23, 77, 54, 33, 98])
np.sort(a)
print(a[a%2==0])

[12 76 54 98]


## 9. 設有 5 個點的坐標，分別為 (6,4), (7,1), (7,4), (3,8), (6,9)。試計算這 5 個點離原點的距離，並依距離來排序這 5 個點（從小排到大）。

In [63]:
a=np.array([[6,7,7,3,6],[4,1,4,8,9]])
dist = np.sqrt(np.sum(a**2, axis=0))
dist_sort = np.argsort(dist)
print(a[:, dist_sort])

[[7 6 7 3 6]
 [1 4 4 8 9]]


## 10. 設
$$
a=
\begin{bmatrix}
5 & 16 & 12 & 1 \\
6 & 11 & 18 & 13 \\
2 & 7 & 3 & 8 \\
\end{bmatrix}
$$
，試依序作答下列各題：

### (a) 將 𝑎 裡的元素從小排到大，排成一個一維陣列。

In [72]:
a=np.array([[5,16,12,1],[6,11,18,13],[2,7,3,8]])
a=np.sort(a,axis=None)
print(a.flatten())

[ 1  2  3  5  6  7  8 11 12 13 16 18]


### (b) 將 𝑎 裡的元素在軸 1（水平）的方向由小到大排序。

In [70]:
a=np.array([[5,16,12,1],[6,11,18,13],[2,7,3,8]])
a=np.sort(a,axis=1)
print(a.flatten())

[ 1  5 12 16  6 11 13 18  2  3  7  8]


### (c) 將陣列 𝑎 的每一列依該列的第一個元素值由小到大排序。排序完的陣列應如下所示：
$$
a=
\begin{bmatrix}
2 & 7  & 3  & 8  \\
5 & 16 & 12 & 1  \\
6 & 11 & 18 & 13 \\
\end{bmatrix}
$$

In [77]:
a=np.array([[5,16,12,1],[6,11,18,13],[2,7,3,8]])
b=np.argsort(a[:, 0])
#print(b)
print(a[b])

[[ 2  7  3  8]
 [ 5 16 12  1]
 [ 6 11 18 13]]


## 10.3 數學矩陣的相關運算

## 11. 試求解下列的方程式：

## (a)
$$
\begin{bmatrix}
    -1  &  2 \\
   1  &  6
\end{bmatrix}
\begin{bmatrix}
    x1  \\
    x2
\end{bmatrix}
=
\begin{bmatrix}
    4  \\
    0
\end{bmatrix}

In [79]:
import numpy.linalg as la
A = np.array([[-1, 2], [1, 6]])
B = np.array([4, 0])
print(la.solve(A,B))

[-3.   0.5]


### (b)
$$
\begin{bmatrix}
    3 & 2 & 4 \\
    5 & 7 & 3 \\
    1 & 6 & 0 \\
\end{bmatrix}
\begin{bmatrix}
    x1  \\
    x2  \\
    x3
\end{bmatrix}
=
\begin{bmatrix}
    -6  \\
    2   \\
    1
\end{bmatrix}
$$

In [80]:
A = np.array([[3, 2,4], [5, 7,3],[1,6,0]])
B = np.array([-6, 2,1])
print(la.solve(A,B))

[ 3.045 -0.341 -3.614]


### (c)
$$
\begin{bmatrix}
    0 & 2 & -2 \\
    7 & 4 & 3 \\
    8 & -4 & -5 \\
\end{bmatrix}
\begin{bmatrix}
    x1  \\
    x2  \\
    x3
\end{bmatrix}
=
\begin{bmatrix}
    17  \\
    12  \\
    16
\end{bmatrix}
$$

In [81]:
A = np.array([[0, 2,-2], [7, 4,3],[8,-4,-5]])
B = np.array([17, 12,16])
print(la.solve(A,B))

[ 1.277  4.08  -4.42 ]


## 12. 試求下列方程式的最小平方解以及殘差：

### (a)
$$
\begin{bmatrix}
    1 & 2\\
    1 & 2\\
    1 & 3\\
\end{bmatrix}
\begin{bmatrix}
    x1  \\
    x2
\end{bmatrix}
=
\begin{bmatrix}
    0  \\
    1   \\
    3
\end{bmatrix}
$$

In [82]:
A = np.array([[1, 2], [1, 2],[1,3]])
B = np.array([0, 1,3])
print(la.lstsq(A,B,rcond=None))

(array([-4.5,  2.5]), array([0.5]), 2, array([4.461, 0.317]))


### (b)
$$
\begin{bmatrix}
    2 & 1 \\
    1 & 2 \\
    1 & 1 \\
\end{bmatrix}
\begin{bmatrix}
    x1  \\
    x2  \\
\end{bmatrix}
=
\begin{bmatrix}
    2  \\
    0   \\
    -3  \\
\end{bmatrix}
$$

In [83]:
A = np.array([[2, 1], [1, 2],[1,1]])
B = np.array([2, 0,-3])
print(la.lstsq(A,B,rcond=None))

(array([ 1., -1.]), array([11.]), 2, array([3.317, 1.   ]))


## 10.4 廣播運算

## 13. 設 𝑎 = (78, 22, 65, 87, 12, 98, 63, 79) 且 𝑥 = 57，試在 𝑎 中找出離 𝑥 最近的數（請寫兩個版本，一個使用 for 迴圈，另一個不要使用 for 迴圈）。

In [114]:
𝑎=np.array([78, 22, 65, 87, 12, 98, 63, 79])
x=57
# for
rd=1E5
for a in a:
    if(abs(a-x)<abs(rd-x)):
        rd=a
print(rd)
# 另解
𝑎=np.array([78, 22, 65, 87, 12, 98, 63, 79])
print(a[np.min(abs(a-x))])

63
63


## 14. 設 𝑐 是由 0 到 255 之間的整數亂數所組成的陣列，形狀為 (3,10)，陣列的每一個直行代表紅、綠藍三個顏色。現有一個顏色 𝑎 = (37, 65, 182)，試找出 𝑐 中，與 𝑎 最相近的顏色（即距離為最短）。


In [148]:
c=np.random.randint(0,256,size=(3,10))
a=np.array([[37],[65],[182]])
print(c)
print(np.argmin(np.sqrt(np.sum((c-a)**2,axis=0))))
print(c[:,np.argmin(np.sqrt(np.sum((c-a)**2,axis=0)))])

[[ 44 224  48 177 139 142 235 128 119 169]
 [183 179 134 199  27 202   9 148 207  69]
 [159  93  78 121  19  25 129  53 251 185]]
0
[ 44 183 159]


## 15. 設陣列 𝑎 和 𝑏 的每個直行代表三維空間中，每一個點的坐標，其內容如下（ 𝑎 有 7 個點，𝑏 有 4 個點）：
$$
a
=
\begin{bmatrix}
    3 & 4 & 8 & 3 & 8 & 9 & 7 \\
    8 & 3 & 5 & 0 & 3 & 2 & 3 \\
    9 & 2 & 4 & 4 & 3 & 6 & 2 \\
\end{bmatrix}
b
=
\begin{bmatrix}
    8 & 7 & 3 & 1\\
    5 & 4 & 4 & 2\\
    4 & 9 & 0 & 6\\
\end{bmatrix}
$$

### (a) 試建立一個 7 × 4 的距離平方表 𝐷（squared distance），其中 𝐷[𝑖,𝑗] 代表 𝑎 裡行索引為𝑖 的點到 𝑏 裡行索引為 𝑗 的點之距離的平方。請利用 for 迴圈撰寫。

In [153]:
a=np.array([[3,4,8,3,8,9,7],[8,3,5,0,3,2,3],[9,2,4,4,3,6,2]])
b=np.array([[8,7,3,1],[5,4,4,2],[4,9,0,6]])
dist=np.zeros((7,4),dtype=int)
for i in range(7):
    for j in range(4):
        dist[i,j]=np.sum((a[:,i]-b[:,j])**2)
print(dist)

[[59 32 97 49]
 [24 59  6 26]
 [ 0 27 42 62]
 [50 57 32 12]
 [ 5 38 35 59]
 [14 17 76 64]
 [ 9 50 21 53]]


### (b) 同習題 (a)，但請利用 Numpy 的廣播來撰寫。

In [158]:
#print(a[:,:,None]-b[:,None,:])
c=np.sum((a[:,:,None]-b[:,None,:])**2,axis=0)
print(c)

[[59 32 97 49]
 [24 59  6 26]
 [ 0 27 42 62]
 [50 57 32 12]
 [ 5 38 35 59]
 [14 17 76 64]
 [ 9 50 21 53]]


### (c) 同習題 (b)，但是距離平方表 𝐷 為一個 4 × 7 的陣列，其中 𝐷[𝑖,𝑗] 代表為 𝑏 裡行索引為𝑖 的點到 𝑎 裡行索引為 𝑗 的點之距離的平方。

In [161]:
a=np.array([[3,4,8,3,8,9,7],[8,3,5,0,3,2,3],[9,2,4,4,3,6,2]])
b=np.array([[8,7,3,1],[5,4,4,2],[4,9,0,6]])
c=np.sum((a[:,None,:]-b[:,:,None])**2,axis=0)
print(c)

[[59 24  0 50  5 14  9]
 [32 59 27 57 38 17 50]
 [97  6 42 32 35 76 21]
 [49 26 62 12 59 64 53]]


## 16. 設一個 4 × 5 的陣列 R 在索引為 (𝑟, 𝑐) 的位置之值為 2𝑟 + 𝑐，即 𝑅[𝑟, 𝑐] = 2r + 𝑐。陣列 R 的內容如下：
$$
𝑅 =
\begin{bmatrix}
0 & 1 & 2 & 3 & 4 \\
2 & 3 & 4 & 5 & 6 \\
4 & 5 & 6 & 7 & 8 \\
6 & 7 & 8 & 9 & 10 \\
\end{bmatrix}
$$

### (a) 試以 for 迴圈建立陣列 R （可能需要兩個 for 迴圈）。

In [162]:
R=np.zeros((4,5),dtype=int)
for i in range(4):
    for j in range(5):
        R[i,j]=2*i+j
print(R)

[[ 0  1  2  3  4]
 [ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]]


### (b) 試以串列生成式來建立陣列 R 。

In [182]:
print(np.array([i*2+j for i in range(4) for j in range(5)]).reshape(4,5))

[[ 0  1  2  3  4]
 [ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]]


### (c) 試以 Numpy 的廣播運算來建立 R 。

In [174]:
R1=np.arange(5).reshape(1,5)
R2=np.arange(0,8,2).reshape(4,1)
print(R1+R2)

[[ 0  1  2  3  4]
 [ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]]


## 10.5 儲存 Numpy 陣列

## 17. 設 𝑎=np.array([1,4,5,7,8])，試依序作答下列各題：

### (a) 試將 𝑎 利用 tobytes() 轉成 bytes 物件，並將結果設定給變數 𝑧。

In [187]:
𝑎=np.array([1,4,5,7,8])
z=a.tobytes()
print(z)

b'\x01\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00'


### (b) 利用 frombuffer() 讀取變數 𝑧 的內容，並驗證結果是否與 𝑎 相同。

In [193]:
b=np.frombuffer(z,dtype=int)
print(b == a)

[ True  True  True  True  True]


### (c) 將陣列 𝑎 的內容利用 save() 存成 example.npy，然後以 load() 讀取檔案 example.npy，驗證看看是否能取回 𝑎 的內容。

In [194]:
np.save('example.npy',a)
np.load('example.npy')

array([1, 4, 5, 7, 8])

### 18. 設 𝑎、𝑏 和 𝑐 為下面 3 個陣列，並依序作答接續的問題：
$$
a=
\begin{bmatrix}
    0 & 2\\
    1 & 6\\
\end{bmatrix}
b=
\begin{bmatrix}
    7 \\
    2 \\
    1 \\
\end{bmatrix}
c=
\begin{bmatrix}
    0 & 2 & 0\\
    6 & 4 & 2\\
    8 & 3 & 4 \\
\end{bmatrix}
$$

### (a) 分別將陣列 𝑎、𝑏 和 𝑐 利用 savez() 存到檔案 variables.npz 中，變數的名稱分別使用 𝑎、𝑏 和 𝑐。

In [184]:
a=np.array([[0,2],[1,6]])
b=np.array([[7],[2],[1]])
c=np.array([[0,2,0],[6,4,2],[8,3,4]])
np.savez('example',a_v=a,b_v=b,c_v=c)

### (b) 讀取 variables.npz，並從中提取出變數 𝑎、 𝑏 和 𝑐的內容。

In [186]:
npz_file=np.load('example.npz')
print(npz_file['a_v'])
print(npz_file['b_v'])
print(npz_file['c_v'])

[[0 2]
 [1 6]]
[[7]
 [2]
 [1]]
[[0 2 0]
 [6 4 2]
 [8 3 4]]
