## 9.1 認識 Numpy 的陣列

## 1. 試依序完成下列各題：

### (a) 試建立一個 4 × 1 的二維陣列 𝑎（行向量），內容為 1.2, 4.3 , 5.4 和 6.7。並分別查詢陣列 𝑎 的形狀（shape）、維度（ndim）和大小（size）。

In [2]:
import numpy as np
a=np.array([[1.2, 4.3 , 5.4 , 6.7]])
print(a)

[[1.2 4.3 5.4 6.7]]


### (b) 同上題，但把 4 × 1 的行向量改為 1 × 4 的列向量。

In [3]:
b=np.array([[1.2],[ 4.3] ,[ 5.4] ,[ 6.7]])
print(b)

[[1.2]
 [4.3]
 [5.4]
 [6.7]]


### (c) 試建立一個 1 × 1 的二維陣列 𝑎，裡面只有一個元素 5，並查詢 𝑎 的形狀、維度和大小。

In [4]:
a=np.array([[5]])
print(a.shape)
print(a.ndim)
print(a.size)

(1, 1)
2
1


### (d) 試建立一個 3 × 4 的二維陣列 𝑎，其中列索引為 0 的元素全為 4，列索引為 1 的元素全為 2，列索引為 2 的元素全為 5。


In [17]:
a=np.tile([4,2,5],(4,1))
print(a)

[[4 2 5]
 [4 2 5]
 [4 2 5]
 [4 2 5]]


## 2. 試建立如下的二維陣列
$$
a=
\begin{bmatrix}
4 & 7 \\
8 & 12 \\
\end{bmatrix}
b=
\begin{bmatrix}
7.4 \\
6.7 \\
2.0 \\
\end{bmatrix}
c=
\begin{bmatrix}
7 & 4\\
6 & 7\\
9 -5 \\
\end{bmatrix}
d=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 \\
\end{bmatrix}
$$

In [19]:
a=np.array([[4,7],[8,12]])
b=np.array([[7.4],[6.7],[2.0]])
c=np.array([[7,4],[6,7],[9,-5]])
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a,b,c,d)

[[ 4  7]
 [ 8 12]] [[7.4]
 [6.7]
 [2. ]] [[ 7  4]
 [ 6  7]
 [ 9 -5]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3. 試建立一個 2 × 3 × 4 的陣列，它可以看成是由 2 頁的 3 × 4 陣列所組成。請將頁索引為 0的元素全設為 0，頁索引為 1 的元素全設為 1。

In [6]:
a=np.array([np.zeros((3,4),dtype='int32'),np.ones((3,4),dtype='int32')])
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


## 4. 試解釋為何 np.array(5).ndim 可以執行，且其結果是 0，而 5.ndim 這個語法則不能執行？

In [7]:
np.array(5).ndim
# 5.ndim 為一個物件

0

## 5. 試建立一個 0 到 1（包含 1），間距為 0.1 的一維陣列。注意此陣列應有 11 個元素。

In [8]:
a=np.arange(0,1,0.1)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## 6. 試建立一個 2 × 3 × 4 的全 0 陣列，型別為 uint8。

In [9]:
a=np.zeros((2,3,4),dtype='uint8')
print(a)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


## 7. 試建立一個 2 × 3 的浮點數亂數陣列，浮點數的數值介於 −1 到 1 之間。

In [10]:
import random
rg=np.random.default_rng(seed=998)
a=rg.standard_normal((2,3))
print(a)

[[ 1.00144974 -0.51872432  0.75331939]
 [-0.13590887 -0.45207455  0.09338439]]


## 8. 試從數字 1 到 20 中隨機挑選 10 個數字，挑選過的數字不可重複挑選。

In [11]:
a=rg.choice(range(20),10,replace=False)
print(a)

[10  9 18  4 14 15 13  1 19  8]


## 9. 設陣列 𝑎 的內容如下，試回答下列各題：
$$
a=
\begin{bmatrix}
0 & 1 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
\end{bmatrix}
$$

### (a) 試從 𝑎 中隨機挑選 8 個數字，挑選的數字不能重複

In [24]:
a=np.array([[0,1,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b=rg.choice(a.flatten(),8,replace=False)
print(b)

[ 7 11 13  0  8 14  5 10]


### (b) 試從 𝑎 中隨機挑選 10 個數字，挑選的數字可以重複。

In [25]:
b=rg.choice(a.flatten(),10)
print(b)

[11  7  1 14  9 14 15  4  8  7]


### (c) 試從 𝑎 中隨機挑選出 2 個不重複的橫列。

In [28]:
b=rg.choice(a.flatten(),2,replace=False)
print(b)

[0 4]


### (d) 將 𝑎 的直行隨機排列。

In [29]:
b=rg.permutation(a,axis=1)
print(b)

[[ 1  4  0  5  3]
 [ 7  9  6 10  8]
 [12 14 11 15 13]]


## 9.2 陣列元素的提取

## 10. 設 𝑎=np.array([23, 67, 54, 26, 92, 88, 53])，試回答下列各題：

### (a) 試提取陣列 𝑎 中，索引為 0、2 和 5 的元素。

In [ ]:
a=np.array([23, 67, 54, 26, 92, 88, 53])
print(a[0],a[2],a[5])

23 54 88


### (b) 試提取陣列 𝑎 中，最後 3 個元素。

In [ ]:
print(a[-3:])

[92 88 53]


### (c) 試提取陣列 𝑎 中，大於 50 的所有元素。

In [ ]:
print(a[a>50])

[67 54 92 88 53]


### (d) 試提取陣列 𝑎 中，索引為奇數的元素。

In [ ]:
print(a[::2])

[23 54 92 53]


### (e) 試提取陣列 𝑎 中，所有的偶數。

In [ ]:
print(a[a%2==0])

[54 26 92 88]


### (f) 試將陣列 𝑎 的元素反向排列。

In [ ]:
print(a[::-1])

[53 88 92 26 54 67 23]


### (g) 試提取索引為 2 到 4 的元素，並將它們反向排列。

In [ ]:
print(a[4:1:-1])

[92 26 54]


## 11. 設 𝑎=np.arange(20).reshape((4, 5))，試回答下列各題：

### (a) 提取陣列 𝑎 中，列索引為 0 到 2，行索引為 1 到 3 的元素。

In [ ]:
a=np.arange(20).reshape((4,5))
b=a[[0,1,2],:][:,[1,2,3]]
print(b)

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


### (b) 提取陣列 𝑎 中，行索引為 2 和 4 的元素。

In [ ]:
b=a[:,[2,4]]
print(b)

[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]]


### (c) 提取陣列 𝑎 中，列索引為 1 到 3 的元素。

In [ ]:
b=a[[1,2,3],:]
print(b)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### (d) 將陣列 𝑎 的直行反向排列。

In [ ]:
b=a[::-1,::]
print(b)

[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


### (e) 取出陣列 𝑎 中，所有可以被 3 整除的數。

In [ ]:
b=a[a%3==0]
print(b)

[ 0  3  6  9 12 15 18]


### (f) 找出陣列 𝑎 中，列與行的索引之和為偶數的所有元素，並將它們放在一個串列裡（本題可能需要撰寫迴圈）。

In [ ]:
lst=a.tolist()
ans=[]
m=0
n=0
for i in lst:
  for j in i:
    if((m+n)%2==0):
      ans.append(j)
    n+=1
  m+=1
  n=0
print(ans)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


### (g) 找出陣列 𝑎 中，可以被 2 整除，但不能被 3 整除的元素共有幾個。

In [ ]:
ans=0
for i in a.tolist():
  for j in i:
    if(j%2==0 and j%3!=0):
      ans+=1
print(ans)

6


## 12. 設 𝑎=np.array([38, 43, 21, 87, 92, 55, 40, 63])，試利用花式索引提取陣列 𝑎 的元素，使其提取後的結果為如下的陣列：

In [ ]:
𝑎=np.array([38, 43, 21, 87, 92, 55, 40, 63])
#(a) array([21, 21, 87, 87])
print(a[[2,2,3,3]])
#(b) array([[21, 21, 87, 87]])
print(a[[[2,2,3,3]]])
#(c) array([[21],
# [21],
# [87],
# [87]])
print(a[[2,2,3,3]].copy().reshape(4,1))
#(d) array([[21, 92, 92],
# [87, 43, 38]])
b=a[[2,4,4,3,1,0]].copy().reshape(2,3)
print(b)
#(e) array([[21, 92],
# [87, 43],
# [55, 87]])
b=a[[2,4,3,1,5,3]].copy().reshape(3,2)
print(b)
#(f) array([[38, 63],
#[38, 63],
#[38, 63]])
b=a[[0,-1,0,-1,0,-1]].copy().reshape(3,2)
print(b)

[21 21 87 87]
[[21 21 87 87]]
[[21]
 [21]
 [87]
 [87]]
[[21 92 92]
 [87 43 38]]
[[21 92]
 [87 43]
 [55 87]]
[[38 63]
 [38 63]
 [38 63]]


## 13. 設 𝑎=np.arange(10,30).reshape(4,5)，試利用花式索引提取陣列 𝑎 的元素，使其提取後的結果為如下的陣列：

In [ ]:
import numpy as np
a=np.arange(10,30).reshape(4,5)
#(a) array([17, 23])
print(a[[1,2],[2,3]])
#(b) array([10, 16, 23])
print(a[[0,1,2],[0,1,3]])
#(c) array([[13, 14],
# [23, 24],
# [28, 29]])
print(a[[0,2,3]][:,[3,4]])
#(d) array([[20, 22, 23],
# [25, 27, 28]])
print(a[[2,3]][:,[0,2,3]])
#(e) array([[10, 12],
# [20, 22]])
print(a[[0,2]][:,[0,2]])
#(f) array([[11, 13, 14],
# [16, 18, 19]])
print(a[[0,1]][:,[1,3,4]])

[17 23]
[10 16 23]
[[13 14]
 [23 24]
 [28 29]]
[[20 22 23]
 [25 27 28]]
[[10 12]
 [20 22]]
[[11 13 14]
 [16 18 19]]


## 14. 設 𝑎=np.array([0,1,2,3,4,5])。在下列各題中，試說明 𝑏 是 𝑎 的一個 view 或是 copy，並驗證您的判斷結果。

In [ ]:
#(a)    b=a[3:]   view
#(b)    b=a[::-1] view
#(c)    b=a.reshape(2,3)  view
#(d)    b=np.random.permutation(a)  copy
#(e)    b=a[[0,3,4]]  view
#(f)    b=a[1:4]  view
#(g)    b=a view
#(h)    b=a.copy()  copy
#(i)    b=np.random.choice(a,4) copy

## 9.3 陣列的進階處理

## 15. 設 𝑎=np.arange(12)，試回答下列各題：

### (a) 查詢陣列 𝑎 的 size, shape, 和 ndim 屬性。

In [ ]:
𝑎=np.arange(12)
print(a.size)
print(a.shape)
print(a.ndim)

12
(12,)
1


### (b) 將 𝑎 分別排成 4 × 3、1 × 12、12 × 1 和 2 × 2 × 3 的陣列。

In [ ]:
print(a.reshape(4,3))
print(a.reshape(1,12))
print(a.reshape(12,1))
print(a.reshape(2,2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


## 16. 設 𝑎=np.arange(12).reshape(3,4)，試回答下列各題（每個小題陣列 𝑎 的內容都一樣）：

### (a) 將陣列 𝑎 拆平成一維陣列

In [ ]:
𝑎=np.arange(12).reshape(3,4)
print(a.reshape(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


### (b) 將陣列 𝑎 重排成 4 × 3 的二維陣列

In [ ]:
print(a.reshape(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### (c) 利用 np.newaxis 增加一個軸給陣列 𝑎 ，使其成為 3 × 1 × 4 的三維陣列。

In [ ]:
print(a[:,np.newaxis,:])
print(a[:,np.newaxis,:].shape)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)


### (d) 將 (c) 的結果利用 copy() 拷貝一份給變數 𝑏 存放，然後試利用 squeeze() 將 𝑏 變成3 × 4 的二維陣列。

In [ ]:
b=a[:,np.newaxis,:].copy()
print(b.squeeze(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### (e) 將陣列 𝑎 的軸 0 和軸 1 互換（swap），並驗證其結果是否等於 𝑎.T？

In [ ]:
a_swap = np.swapaxes(a, 0, 1)
print(np.array_equal(a_swap, a.T))

True


### (f) 將陣列 𝑎 的軸 1 移到軸 0，並驗證其結果是否等於 𝑎.T？

In [ ]:
a_swap = np.swapaxes(a, 1, 0)
print(np.array_equal(a_swap, a.T))

True


### (g) 將陣列 𝑎 切割成兩個等份且水平並排的陣列。

In [ ]:
for i, arr in enumerate(np.hsplit(a, 2)):
  print(f"陣列 {i + 1}:\n", arr)

陣列 1:
 [[0 1]
 [4 5]
 [8 9]]
陣列 2:
 [[ 2  3]
 [ 6  7]
 [10 11]]


### (h) 將陣列 𝑎 沿軸 0 的方向切割成兩個垂直的陣列，其大小分別為 1 × 4 和 2 × 4

In [ ]:
for i, arr in enumerate(np.vsplit(a, [1])):
  print(f"陣列 {i + 1}:\n", arr)

陣列 1:
 [[0 1 2 3]]
陣列 2:
 [[ 4  5  6  7]
 [ 8  9 10 11]]


## 17. 設 𝑎=np.arange(24).reshape(2,3,4)，試回答下列各題（每個小題陣列 𝑎 的內容都一樣）：

### (a) 在陣列 𝑎 的軸 0 位置新增一個軸，使其成為 1 × 2 × 3 × 4 的四維陣列。

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
a=a[np.newaxis, :, :, :]
print(a)

[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]]


### (b) 將陣列 𝑎 的軸 0 和軸 2 互換，並驗證其結果是否等於 a.T。

In [ ]:
a=np.swapaxes(a, 0, 2)
print(np.array_equal(a, a.T))

False


### (c) 將陣列 𝑎 的軸 2 移到軸 0，並說明這個和 (b) 的結果為何不同。

In [ ]:
a=np.moveaxis(a, 2, 0)
# (b) 和 (c) 的結果不同，因為 swapaxes 只是互換兩個軸的順序，而 moveaxis 可以移動軸到指定的位置。

### (d) 將陣列 𝑎 在軸 0 的方向切割成 2 個等份。

In [ ]:
𝑎=np.arange(24).reshape(2,3,4)
print(np.split(a,2,axis=0))

[array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]]), array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])]


### (e) 將陣列 𝑎 分割成兩個 2 × 3 × 2 的陣列。

In [ ]:
𝑎=np.arange(24).reshape(2,3,4)
print(np.split(a,2,axis=2))

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


### (f) 將陣列 𝑎[0]（形狀為 3 × 4 ）和 𝑎[1]（形狀為 3 × 4 ）分別在垂直方向和水平方向合併（合併後應該分別是 6 × 4 和 3 × 8 的陣列）。

In [ ]:
r1 = np.vstack((a[0], a[1]))  # 在垂直方向合併
r2 = np.hstack((a[0], a[1]))  # 在水平方向合併
print(r1)
print(r2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
